samarthhapse/sarthi

server/.gitignore, server/config/connection.js, server/controllers/expert-controller.js, server/controllers/student-controller.js, server/index.js, server/middleware/isAuthenticated.js, server/models/expert-model.js, server/models/student-model.js, server/package-lock.json, server/package.json, server/routes/expertRoute.js, server/routes/studentRoute.js
I have initialized the backend using MVC structure, moreover I have written the backend for student and expert.
The controllers for register, login, change password , get details of all experts/students and get details of a single expert/ student is implemented successfully.
issue no #24 is now completed.
I have worked on this under GSSOC'24.
=> backend initialized

client/package-lock.json, client/package.json, client/postcss.config.js, client/src/App.css, client/src/App.jsx, client/src/components/api/expertapi.js, client/src/components/api/studentapi.js, client/src/components/expert/ExpertForget.jsx, client/src/components/expert/ExpertLogin.jsx, client/src/components/expert/ExpertSignup.jsx, client/src/components/home/ExpertHome.jsx, client/src/components/home/StudentHome.jsx, client/src/components/landing/Landing.jsx, client/src/components/student/StudentForget.jsx, client/src/components/student/StudentLogin.jsx, client/src/components/student/StudentSignup.jsx, client/src/index.css, client/tailwind.config.js, server/controllers/student-controller.js, server/middleware/isAuthenticated.js
=> build frontend authorization section according to backend requirements

client/src/components/Landing/HomePage.jsx
Fixes : #77 
I have added dark / light mode button in the site and pushed the changes in temp branch
Have a look
https://github.com/samarthhapse/sarthi/assets/119691733/3f9ba5c6-4388-4c03-94cb-07889613f7bf
=> added dark/light mode button

client/src/components/preloader/Preloader.jsx, client/src/main.jsx
Fixes: #98 
I have fixed preloader issue and now it is perfectly working . Kindly add GSSoC and level labels and add me as the assignee to this PR .
=> fixed preloader issue

client/src/App.css, client/src/components/Landing/HomePage.jsx, client/src/components/auth/Landing.jsx, client/src/components/auth/expert/ExpertLogin.jsx, client/src/components/auth/expert/ExpertSignup.jsx, client/src/components/auth/student/StudentLogin.jsx, client/src/components/auth/student/StudentSignup.jsx
Added Beautiful Animations on all required pages.
Used farmer motion to animate because it is already have installed in this project.
#91 this required issue is resolved here.
https://github.com/samarthhapse/sarthi/assets/78371075/5cb3214a-5e95-45a0-b920-e33199aab227
=> Added animations #91

client/src/App.css, client/src/components/Landing/HomePage.jsx, client/src/components/auth/Landing.jsx, client/src/components/auth/expert/ExpertLogin.jsx, client/src/components/auth/expert/ExpertSignup.jsx, client/src/components/auth/student/StudentLogin.jsx, client/src/components/auth/student/StudentSignup.jsx
Reverts samarthhapse/sarthi#108
=> Revert "Added animations #91"

client/src/components/auth/Landing.jsx, client/src/components/auth/expert/ExpertLogin.jsx, client/src/components/auth/expert/ExpertSignup.jsx, client/src/components/auth/student/StudentLogin.jsx, client/src/components/auth/student/StudentSignup.jsx
Please merge.
https://github.com/samarthhapse/sarthi/assets/78371075/ea63e317-a90a-4b9c-9b6c-8aee91e5a6f2
=> Added All the required animation

client/src/App.css, client/src/components/Landing/HomePage.jsx
I this PR I have fixed the app UI.
This PR is for #107 
Please merge, after this I will work on dark mode UI of signIn and signUp
=> fixed the UI of whole app #107

client/src/components/Basic/Navbar.jsx
=> home page linked added to navbar

client/src/App.jsx, client/src/components/Basic/Faq.jsx
=> added text-color toggle for dark mode

client/src/components/home/StudentHome.jsx, client/src/components/home/studentHome/ExpertCard.jsx, client/src/components/home/studentHome/ExpertiseCard.jsx, client/src/components/home/studentHome/ExpertsByExpertise.jsx, server/config/connection.js, server/controllers/expert-controller.js, server/index.js
fixes #140 
added feature so that a student can search for experts based on the selected expertise
=> add get experts by expertise

client/src/components/Basic/Logo.jsx, client/src/components/Basic/Navbar.jsx
I have created a logo component for reusability and changed logo as required.
=> Logo change

client/src/components/auth/expert/ExpertSignup.jsx, client/src/components/auth/student/StudentForget.jsx, client/src/components/auth/student/StudentSignup.jsx, client/src/components/providers/ThemeProvider.jsx
Please merge this pr will solve #164
=> Default dark mode#164

client/src/components/auth/expert/ExpertLogin.jsx, client/src/components/auth/student/StudentLogin.jsx
Solved issue #176 
https://github.com/samarthhapse/sarthi/assets/154724111/72c477e9-376a-4d7b-a1d4-e971211bbebd
=> Added eye in pw field in student & expert login

server/controllers/chat-controller.js, server/controllers/message-controller.js, server/index.js, server/models/chat-model.js, server/models/message-model.js, server/package-lock.json, server/package.json, server/routes/chatRoute.js, server/routes/messageRoute.js
I have implemented the backend for chat functionality. Resolved the issue #11.
=> Chat functionality backend

client/src/components/auth/expert/ExpertSignup.jsx, client/src/components/auth/student/StudentSignup.jsx
=> Added eye feature for signup

client/src/App.jsx, client/src/components/Basic/Navbar.jsx, client/src/components/api/basicapi.js, client/src/components/chat/ChatParticipant.jsx, client/src/components/chat/Chats.jsx, server/controllers/chat-controller.js, server/controllers/message-controller.js, server/index.js, server/models/chat-model.js, server/routes/chatRoute.js
=> add view chats

client/index.html
Added the feature multilingual translation.
=> Gtranslator

client/src/components/home/StudentHome.jsx, client/src/components/home/studentHome/ExpertCard.jsx, client/src/components/profile/ExpertProfile.jsx
Solved issue #223 
https://github.com/user-attachments/assets/db2823ad-43b9-4723-8148-92ba92c38d83
=> Added pay now button in expert details page

client/src/App.jsx, client/src/components/Landing/HomePage.jsx, client/src/components/meet/CreateMeeting.jsx, client/src/components/meet/JoinMeeting.jsx, client/src/components/meet/Room.jsx, client/src/components/meet/VideoRoom.jsx, server/package-lock.json, server/package.json, server/webSocket/webSocket.js
Integration of online meeting feature (MERN stack)
fixes issue: 215
first of all thanks for believing in me and I am sorry for the delay, as per your given time I am submitting it accordingly.
thanks @samarthhapse
=> added the expert student conference meet room

client/src/components/Basic/Navbar.jsx, client/src/components/auth/Landing.jsx, client/src/components/auth/student/StudentLogin.jsx, client/src/components/auth/student/StudentSignup.jsx
=> Made the login/signup page responsive and added the hamburger menu for navbar

client/src/components/Landing/HomePage.jsx, client/src/components/meet/CreateMeeting.jsx, client/src/components/profile/ExpertProfile.jsx, server/index.js, server/routes/meetRouter.js
=> updated backend

client/src/components/profile/ExpertProfile.jsx
Solved issue #230 
https://github.com/user-attachments/assets/03878668-0f55-4568-9cfa-e40548815cd4
=> Added amount input field for payment 

server/controllers/auth-expert.js, server/controllers/expert-controller.js, server/models/confirmationCode-model.js, server/routes/expertRoute.js
The routes must be handled by the front end developer carefully and first the expert should get confirmation then only he should be allowed to see the register page and the rest of the process can go on smoothly .
The OWNER just needs to click on the route or some kind of link can be made and he just needs to enter the email and the name of the expert the code will be send to the expert automatically and all the other process are being handled by the user .
once the code is being confirmed the data from the expert document [MODEL] and the code document [MODEL] will be removed.
AUTH-EXPERT and EXPERT_ROUTES can alone handle the whole process .
=> expert authorization
